name: Testing Django 6.0


on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  Django60:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - '3.14.2'
          - '3.13.11'
          - '3.12.12'
        django-version:
          - '6.0.2'
        database-target:
          - 'mysql'
          - 'postgres'
          - 'sqlite'

    env:
      DATABASE_ENGINE: ${{ matrix.database-target }}
      DJANGO_VERSION: ${{ matrix.django-version }}

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: gh_actions_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gh_actions_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6

      - name: Install the latest version of `uv`
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: "auto"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync
          uv pip install Django==${{ matrix.django-version }}

      - name: Install dependencies (if mysql)
        if: ${{ matrix.database-target == 'mysql' }}
        run: |
          uv pip install mysqlclient

      - name: Install dependencies (if postgres)
        if: ${{ matrix.database-target == 'postgres' }}
        run: |
          uv pip install psycopg2

      - name: Environment Report
        run: |
          echo Python Version ... $(python --version)
          echo Django Version ... ${DJANGO_VERSION}
          echo Database Used .... ${DATABASE_ENGINE}

      - name: Unit Testing
        run: make test-unit

      - name: Coverage Report
        run: make test-coverage-report

      - name: Local Integration Testing
        run: make test-integration

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml

      - name: Upload test results to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: junit.xml
          report_type: test_results
